### ISSUE TITLE
Feature Request: Base64Encode should allow binary data

### ISSUE THREAD

**Issue by hschneider** [egoist/toolcat-releases#12]
I mostly use base64encode to encode images and other assets, which is the main purpose of this kind of encoding.
Would be nice to have a file open dialog or better drag and drop, to encode such files.

**Comment by egoist** [comment]
you can drag and drop text files into the editor, does it work for you? if not are you using Windows?

**Comment by egoist** [comment]
oh I see you are encoding images, it's not supported yet, but I'm releasing `Image to Base64` soon, do you want support for other files?

**Comment by hschneider** [comment]
Thanks! IMHO it makes sense to all binary files. 
Base64Encoding is my favorite encoding when transporting binary data of any kind with e.g. JSON over the network.

**Comment by egoist** [comment]
what is your use case for that? such as transferring a mp4 file in base64 over the network

**Comment by hschneider** [comment]
I have currently 2 use cases:
1. Encode image resources to strings and embed them in source code, to avoid loading external file assets. Currently I prepare these files via commandline.
2. Using custom JSON based API protocols to save binary data of any kind in a database. Here I encode these files via code on the fly, but having it in ToolCat would be helpful to generate test data.

So the most needed use case would be image encoding: jpg, gif, png and svg.
Other users might prefer other file types ...

**Comment by egoist** [comment]
Image to Base64 is available now in https://github.com/egoist/toolcat-releases/releases/tag/v0.2.19

**Comment by hschneider** [comment]
Great! Thanks!
