### ISSUE TITLE
Adding CURL -> language converter + recommendations

### ISSUE THREAD

**Issue by doroved** [egoist/toolcat-releases#4]
1. It would be cool if you add a similar tool - https://curlconverter.com/rust/ (you can do more than just rust.)
2. I recommend to categorize tools in the sidebar.
3. use this recommendation to remove interface jumps when scrolling - https://x.com/doroved/status/1716366073623138754?s=20.

**Comment by egoist** [comment]
cool 👍

**Comment by egoist** [comment]
Actually I didn't notice the scrolling issues, can you point it out?

**Comment by doroved** [comment]
> Actually I didn't notice the scrolling issues, can you point it out?


https://github.com/egoist/toolcat-releases/assets/30116541/c7f15123-9cbe-410a-a0be-715c84cbd386

**Comment by egoist** [comment]
how do you reproduce that? just scroll with the mouse? I couldn't reproduce it 😢

**Comment by egoist** [comment]
ok. got it now. you mean scrolling with the touchpad

**Comment by egoist** [comment]
0.2.2
